const competitorNames = [
  "HypeAuditor",
  "Kofluence",
  "Qoruz",
  "Drim",
  "AnyMind",
  "Anymind",
  "Influencer Marketing Hub",
  "Territory Influence",
  "Vero",
  "Upfluence",
  "AspireIQ",
  "Later",
  "Grin",
  "CreatorIQ",
  "Tagger",
  "NeoReach",
  "Mavrck",
  "Sprout Social",
  "Meltwater",
  "Popular Pays",
  "Viral Nation",
  "Obviously",
  "Revuze",
  "AWISEE",
  "Cube Asia",
  "Collab Asia",
  "Kobe",
  "AsiaInfluencerX",
  "Narrators",
  "CastingAsia",
  "Bangkok Elite Marketing",
  "Digital Business Lab",
  "LYFE Marketing",
  "Kindred",
  "impact.com",
  "The Influencer Marketing Factory",
  "inBeat",
  "TAMLO",
  "DFY",
  "Copyleft",
  "TrueVibe",
  "One Impression",
  "Fastmoss",
  "KolaData",
  "koladata",
]

const escapeRegExp = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")

export const bannedMatchers = [
  { label: "Nano influencer", regex: /\bnano\s*-?influencer\b/i },
  { label: "Nano creator", regex: /\bnano\s*-?creator\b/i },
  { label: "AI", regex: /\bai\b/i },
  { label: "Artificial intelligence", regex: /\bartificial\s+intelligence\b/i },
  { label: "Livestream", regex: /\blive[-\s]?stream\b/i },
  { label: "ToB", regex: /\bToB\b/i },
  { label: "to-b", regex: /\bto-?b\b/i },
  { label: "Brand in-house team", regex: /\bbrand\s+in[-\s]?house\s+team\b/i },
  { label: "In-house team", regex: /\bin-house\s+team\b/i },
  { label: "Builder team", regex: /\bbuilder\s+team\b/i },
  ...competitorNames.map(name => ({ label: name, regex: new RegExp(`\\b${escapeRegExp(name)}\\b`, "i") })),
]

export const focusAreaOptions = [
  { id: "industry-news", label: "Industry news impact" },
  { id: "policy-impact", label: "Policy / platform change impact" },
  { id: "attribution", label: "Tri-party attribution update" },
  { id: "series", label: "Series installment" },
  { id: "authority-shift", label: "Authority myth busting" },
  { id: "platform-ops", label: "Platform algorithm & format" },
  { id: "localization", label: "Localization strategy" },
  { id: "integration", label: "Cross-platform integration" },
  { id: "economy", label: "Influencer economy analysis" },
]

export const priorityFocusIds: string[] = ["industry-news", "policy-impact", "attribution"]

export const recommendedHashtags = [
  "#SoutheastAsiaMarketing",
  "#IndiaInfluencers",
  "#APACBrands",
  "#InfluencerMarketing",
  "#DigitalStrategy",
  "#SocialCommerce",
  "#MarketingTrends",
  "#BrandStrategy",
  "#CrossCultural",
  "#MarketingInsights",
  "#InfluencerROI",
  "#CampaignOptimization",
]

export const finalChecklistItems = [
  "已读取Final_Post.md并记录重复主题，包含内容、数据都没有和已经post过的相同",
  "确认与Final_Post.md相似度<30%",
  "包含行业重要新闻或重大事件影响分析",
  "所有数据来自最近7天内",
  "无竞品/nano词汇",
  "10篇不同风格",
  "包含B2B吸引策略",
]
